= Relaton-XSF: bibliographic retrieval of XMPP XEP specifications

image:https://img.shields.io/gem/v/relaton-xsf.svg["Gem Version", link="https://rubygems.org/gems/relaton-xsf"]
image:https://github.com/relaton/relaton-xsf/workflows/macos/badge.svg["Build Status (macOS)", link="https://github.com/relaton/relaton-xsf/actions?workflow=macos"]
image:https://github.com/relaton/relaton-xsf/workflows/windows/badge.svg["Build Status (Windows)", link="https://github.com/relaton/relaton-xsf/actions?workflow=windows"]
image:https://github.com/relaton/relaton-xsf/workflows/ubuntu/badge.svg["Build Status (Ubuntu)", link="https://github.com/relaton/relaton-xsf/actions?workflow=ubuntu"]
image:https://codeclimate.com/github/relaton/relaton-xsf/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/relaton/relaton-xsf"]
image:https://img.shields.io/github/issues-pr-raw/relaton/relaton-xsf.svg["Pull Requests", link="https://github.com/relaton/relaton-xsf/pulls"]
image:https://img.shields.io/github/commits-since/relaton/relaton-xsf/latest.svg["Commits since latest",link="https://github.com/relaton/relaton-xsf/releases"]

== Purpose

`relaton-xsf` provides bibliographic information of XMPP XEP specifications using the
https://github.com/relaton/relaton-models#the-relaton-bibliographic-models[BibliographicItem model].

== Data sources

Relaton-XSF retrieves bibliographic information from https://xmpp.org/extensions/refs/[XMPP dataset].

The XSF Library dataset provides documents listed in the https://github.com/relaton/relaton-data-xsf/blob/main/index-v1.yaml[index].

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'relaton-xsf'
----

And then execute:

    $ bundle

Or install it yourself as:

    $ gem install relaton-xsf

== Usage

=== Search for a standard using keywords

[source,ruby]
----
require 'relaton_xsf'
=> true

hit_collection = RelatonXsf::Bibliography.search("XEP 0001")
=> <RelatonXsf::HitCollection:0x00000000019780 @ref=XEP 0001 @fetched=false>

item = hit_collection[0].fetch
=> #<RelatonXsf::BibliographicItem:0x000000011167a518
 ...
----

=== XML serialization
[source,ruby]
----
item.to_xml
=> "<bibitem id="XEP0001" type="standard" schema-version="v1.2.9">
      <fetched>2023-07-18</fetched>
      <title format="text/plain" language="en" script="Latn">XMPP Extension Protocols</title>
      ...
    <bibitem>"
----
With argument `bibdata: true` it outputs XML wrapped by `bibdata` element and adds flavor `ext` element.
[source,ruby]
----
item.to_xml bibdata: true
=> "<bibdata type="standard" schema-version="v1.2.9">
      <fetched>2023-07-18</fetched>
      <title format="text/plain" language="en" script="Latn">XMPP Extension Protocols</title>
      ...
      <ext>
        <doctype>rfc</doctype>
      </ext>
  </bibdata>"
----

=== Get document by reference
[source,ruby]
----
item = RelatonXsf::Bibliography.get "XEP 0001"
[relaton-xsf] (XEP 0001) Fetching from Relaton repository ...
[relaton-xsf] (XEP 0001) Found `XEP 0001`
=> #<RelatonXsf::BibliographicItem:0x000000011275cd18
...

item.docidentifier.first.id
=> "XEP 0001"
----

=== Typed links

XSF publications have `src` type link.

[source,ruby]
----
item.link
=> [#<RelatonBib::TypedUri:0x0000000113ad5ca0
  @content=#<Addressable::URI:0xcc24 URI:http://xmpp.org/extensions/xep-0001.html>,
  @language=nil,
  @script=nil,
  @type="src">]
----

=== Fetch data

This gem uses the https://xmpp.org/extensions/refs/ dataset as a data source.

The method `RelatonXsf::DataFetcher.fetch(output: "data", format: "yaml")` fetches all the documents from the dataset and saves them to the `./data` folder in YAML format.
Arguments:

- `output` - folder to save documents (default './data').
- `format` - the format in which the documents are saved. Possible formats are: `yaml`, `xml`, `bibxxml` (default `yaml`).

[source,ruby]
----
RelatonXsf::DataFetcher.fetch
Started at: 2021-09-01 18:01:01 +0200
Stopped at: 2021-09-01 18:01:43 +0200
Done in: 42 sec.
=> nil
----

=== Logging

RelatonXsf uses the relaton-logger gem for logging. By default, it logs to STDOUT. To change the log levels and add other loggers, read the https://github.com/relaton/relaton-logger#usage[relaton-logger] documentation.

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/metanorma/relaton-xsf.

== License

The gem is available as open source under the terms of the https://opensource.org/license/bsd-2-clause/[2-Clause BSD License].
